import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../dist');
const read=name=>readFileSync(resolve(root,name),'utf8');
const write=(name,s)=>writeFileSync(resolve(root,name),s);
const identity='Spectra Rental, unidad de negocios de Mentora International S.A.C., identificada con RUC N.° 20614487268.';
const wa=(service)=>'https://wa.me/51920384374?text='+encodeURIComponent(`Hola, deseo solicitar una propuesta de ${service}.\n\n${identity}\n\nTipo de evento:\nFecha:\nRecinto en Lima Metropolitana:\nRequerimiento:`);
const btn=(label,href,ghost=false)=>`<a class="btn ${ghost?'btn--ghost':'btn--primary'}" href="${href}"${href.startsWith('https:')?' target="_blank" rel="noopener"':''}>${label}</a>`;
const fig=(key,alt,priority=false)=>`<figure class="av-photo av-photo--${key}"><img src="assets/audiovisual/${key}.webp" srcset="assets/audiovisual/${key}-720.webp 720w, assets/audiovisual/${key}.webp 1600w" sizes="(max-width: 700px) 100vw, 1180px" alt="${alt} — imagen referencial" width="1600" height="${({home:1066,sound:1070,lighting:1066,integrated:997})[key]}" ${priority?'fetchpriority="high"':'loading="lazy" decoding="async"'}><figcaption>Imagen referencial · No corresponde a un proyecto de Spectra Rental.</figcaption></figure>`;
const services=[['pantallas-led.html','led','Pantallas LED'],['sonido.html','sound','Sonido'],['iluminacion.html','lighting','Iluminación'],['soluciones-audiovisuales.html','integrated','Soluciones audiovisuales']];
const header=`<header class="site-header"><div class="container nav-shell"><a class="brand" href="index.html" aria-label="SPECTRA RENTAL, inicio"><img src="assets/brand/spectra-logo.png" alt="SPECTRA RENTAL"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav" aria-label="Abrir menú"><span></span><span></span><span></span></button><nav class="nav-links" id="main-nav" aria-label="Navegación principal"><a href="index.html" data-nav="home">Inicio</a><details class="nav-services"><summary>Servicios</summary><div class="nav-service-list">${services.map(([url,key,label])=>`<a href="${url}" data-nav="${key}">${label}</a>`).join('')}</div></details><a href="publicidad-led.html" data-nav="advertising">Publicidad LED</a><a href="nosotros.html" data-nav="about">Nosotros</a><a href="contacto.html" data-nav="contact">Contacto</a><a class="nav-cta" href="contacto.html#solicitudes">Cotizar</a></nav></div></header>`;
const base=read('contacto.html');
const footer=base.match(/<footer class="site-footer">[\s\S]*?<\/footer>/)[0];
function page(file,key,title,description,main){
 const head=base.slice(0,base.indexOf('<body')).replace(/<title>[\s\S]*?<\/title>/,`<title>${title} | SPECTRA RENTAL</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${description}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${title} | SPECTRA RENTAL">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${description}">`);
 write(file,`${head}<body data-page="${key}"><a class="skip-link" href="#contenido">Saltar al contenido</a>${header}<main id="contenido">${main}</main>${footer}<a class="wa-float" href="${wa('servicios audiovisuales')}" target="_blank" rel="noopener" aria-label="Consultar por WhatsApp">WA<span>Consultar por WhatsApp</span></a><script src="js/script.js" defer></script></body></html>`);
}
page('index.html','home','Servicios audiovisuales para eventos en Lima','Pantallas LED, sonido, iluminación y soluciones audiovisuales coordinadas en Lima Metropolitana. Conoce los servicios de SPECTRA RENTAL y solicita una propuesta.',`
<section class="av-home-intro"><div class="container"><p class="eyebrow">SPECTRA RENTAL · Lima Metropolitana</p><div class="av-home-heading"><h1>Soluciones audiovisuales<br>para eventos <span class="av-accent">y marcas.</span></h1><div><p>Comercializamos y coordinamos pantallas LED, sonido e iluminación. Reunimos los servicios que requiere tu producción y definimos su alcance desde un solo punto de contacto.</p>${btn('Cotizar mi proyecto','contacto.html#solicitudes')}</div></div>${fig('home','Vista panorámica de un evento con producción audiovisual',true)}<div class="av-home-caption"><span>Eventos corporativos · Activaciones · Conferencias · Conciertos</span><span>Atención previa coordinación</span></div></div></section>
<section class="av-home-directory av-space"><div class="container av-directory-layout"><div><p class="eyebrow">Áreas de servicio</p><h2>Elige el punto<br>de partida.</h2><p>Un requerimiento puntual o varios componentes en conjunto: cada proyecto tiene una ruta de atención.</p></div><nav aria-label="Explorar servicios" class="av-directory">
<a href="pantallas-led.html"><span>01</span><strong>Pantallas LED</strong><small>La solución visual del evento</small></a>
<a href="sonido.html"><span>02</span><strong>Sonido profesional</strong><small>Audio para público y escenario</small></a>
<a href="iluminacion.html"><span>03</span><strong>Iluminación</strong><small>Luz aplicada al espacio y la escena</small></a>
<a href="soluciones-audiovisuales.html"><span>04</span><strong>Soluciones audiovisuales</strong><small>Varios servicios, una coordinación</small></a>
<a href="publicidad-led.html"><span>05</span><strong>Publicidad LED</strong><small>Contratación de espacios para marcas</small></a></nav></div></section>
<section class="av-home-note av-space" id="como-trabajamos"><div class="container"><p class="eyebrow">Definición del proyecto</p><h2>Primero, el objetivo.<br>Después, la propuesta.</h2><div class="av-home-note-columns"><p>Partimos de lo que necesitas comunicar, del tipo de público y de la dinámica del encuentro. Así delimitamos qué servicios conviene considerar.</p><p>Recibirás una propuesta con el alcance a contratar. La fecha, las condiciones del recinto y los requerimientos de producción orientan la evaluación comercial y técnica.</p></div><a class="text-link" href="eventos.html">Revisar aplicaciones por tipo de evento</a></div></section>`);

page('sonido.html','sound','Sonido profesional para eventos en Lima','Sonorización, microfonía y operación de audio para eventos en Lima. SPECTRA RENTAL evalúa el recinto y el programa para preparar una propuesta de sonido.',`
<section class="av-sound-opening"><div class="container"><div class="av-sound-label"><p class="eyebrow">Sonido profesional</p><span>Voz · Música · Reproducción</span></div>${fig('sound','Consola y operación de audio profesional para eventos',true)}<div class="av-sound-title"><h1>Que cada intervención<br>se escuche <span class="av-accent">con claridad.</span></h1><p>El audio debe responder al programa, al público y al recinto. Estructuramos la sonorización de tu evento considerando cómo se hablará, qué se reproducirá y dónde debe escucharse.</p></div></div></section>
<section class="av-sound-scope av-space"><div class="container av-sound-layout"><div class="av-sound-side"><p class="eyebrow">Del escenario al público</p><h2>Un sistema definido<br>por su uso.</h2><p>La propuesta puede contemplar los siguientes componentes, según la evaluación y el alcance contratado.</p></div><dl class="av-audio-list"><div><dt>Captación</dt><dd>Microfonía de acuerdo con el número de intervenciones y la dinámica: ponencia, panel, conducción o presentación.</dd></div><div><dt>Mezcla y reproducción</dt><dd>Consola, fuentes de audio y manejo de señales para combinar voces, música y piezas audiovisuales.</dd></div><div><dt>Distribución y monitoreo</dt><dd>Planteamiento del sistema para las zonas de público y las necesidades de escucha en escenario.</dd></div><div><dt>Operación</dt><dd>Coordinación de pruebas y atención de los cambios de audio previstos durante el programa.</dd></div></dl></div></section>
<section class="av-audio-brief av-space"><div class="container"><div><p class="eyebrow">Para evaluar tu requerimiento</p><h2>Compártenos el programa<br>y las condiciones del lugar.</h2></div><div><ul><li>Recinto cerrado o abierto y distribución del público.</li><li>Cantidad de participantes que usarán micrófono.</li><li>Presentaciones musicales, pistas o intervenciones en vivo.</li><li>Horarios de instalación, pruebas y actividad.</li></ul><p>Equipos y configuración se precisan en la cotización; esta página no representa un inventario disponible.</p>${btn('Solicitar propuesta de sonido',wa('sonido profesional'))}<a class="text-link" href="soluciones-audiovisuales.html">Coordinar audio con otros servicios</a></div></div></section>`);

page('iluminacion.html','lighting','Iluminación profesional para eventos en Lima','Iluminación escénica y ambiental para eventos corporativos y producciones en Lima. Define con SPECTRA RENTAL una propuesta según el espacio y el programa.',`
<section class="av-light-opening"><div class="container"><p class="eyebrow">Iluminación profesional</p><h1>La luz organiza<br>lo que el público <span class="av-accent">ve.</span></h1><p>Planteamos la iluminación según el protagonismo de las personas, la lectura del escenario y el ambiente que requiere cada momento.</p></div></section>
<section class="av-light-story" aria-labelledby="light-scene"><div class="av-light-photo">${fig('lighting','Iluminación escénica aplicada a una producción en un recinto de eventos',true)}</div><div class="av-light-editorial"><article><span>ESCENA</span><h2 id="light-scene">Dirigir la atención.</h2><p>Una intervención, una presentación o un acto protocolar necesitan una lectura visual definida. Evaluamos posiciones y zonas de luz en relación con el desarrollo del evento.</p></article><article><span>AMBIENTE</span><h2>Dar coherencia al espacio.</h2><p>La propuesta ambiental considera el recinto, la identidad del encuentro y la convivencia con pantallas y otros elementos visuales.</p></article><article><span>SECUENCIA</span><h2>Acompañar cada momento.</h2><p>Los cambios, efectos y transiciones se plantean según el programa. La operación y programación se delimitan en el servicio contratado.</p></article></div></section>
<section class="av-light-request av-space"><div class="container"><div><p class="eyebrow">Antes de definir las posiciones</p><h2>El recinto también<br>forma parte del diseño.</h2><p>Comparte fotografías o un plano, horarios, zonas a destacar y referencias del ambiente buscado. Revisaremos montaje, energía y relación con el escenario antes de precisar equipos.</p></div><div>${btn('Cotizar iluminación',wa('iluminación profesional'))}<a class="text-link" href="soluciones-audiovisuales.html">Integrar iluminación con la producción</a></div></div></section>`);

page('soluciones-audiovisuales.html','integrated','Soluciones audiovisuales integrales en Lima','Coordina pantallas LED, sonido, iluminación y soporte técnico en una propuesta audiovisual para tu evento. Alcance definido según los requerimientos del proyecto.',`
<section class="av-integrated-opening av-space"><div class="container"><p class="eyebrow">Soluciones audiovisuales integrales</p><h1>Varios componentes.<br><span class="av-accent">Una producción coordinada.</span></h1><div class="av-integrated-intro"><p>Cuando el evento necesita imagen, audio y luz, las decisiones deben tomarse en conjunto. SPECTRA RENTAL estructura una propuesta combinada a partir del brief y coordina los servicios incluidos en su alcance.</p><a class="btn btn--primary" href="#alcance">Definir los componentes</a></div></div></section>
<section class="av-integration-map" id="alcance" aria-labelledby="integration-title"><div class="container"><h2 id="integration-title">Lo que debe funcionar<br>en conjunto.</h2><div class="av-map"><div class="av-map-core"><p class="eyebrow">Punto de partida</p><h3>Tu programa<br>de producción</h3><p>Objetivo, recinto, contenido y horarios.</p></div><div class="av-map-rows"><a href="pantallas-led.html"><strong>Imagen</strong><span>Formato visual y ubicación de las pantallas LED.</span></a><a href="sonido.html"><strong>Audio</strong><span>Intervenciones, reproducción y necesidades de escucha.</span></a><a href="iluminacion.html"><strong>Luz</strong><span>Escena, ambiente y transiciones previstas.</span></a></div></div><p class="av-map-note">Puedes solicitar una combinación de servicios. No se presupone que todos los componentes sean necesarios ni estén incluidos.</p></div></section>
<section class="av-integrated-production av-space"><div class="container">${fig('integrated','Escenario que integra pantallas, sistemas de sonido e iluminación')}<div class="av-production-caption"><h2>El alcance,<br>por escrito.</h2><div><p>La propuesta identifica los servicios considerados, los requerimientos del lugar y las responsabilidades de coordinación. Los horarios de montaje, pruebas, función y retiro se revisan como parte de un mismo programa.</p><p>El soporte técnico se vincula a los servicios contratados. Las necesidades adicionales se evalúan antes de confirmar el proyecto.</p>${btn('Planificar solución audiovisual',wa('una solución audiovisual integral'))}</div></div></div></section>`);

page('contacto.html','contact','Contacto y cotizaciones audiovisuales','Solicita una propuesta de pantallas LED, sonido, iluminación, producción integral o publicidad LED. WhatsApp +51 920 384 374. Lima Metropolitana, previa coordinación.',`
<section class="av-contact av-space"><div class="container"><p class="eyebrow">Contacto comercial</p><h1>Conversemos sobre<br>tu requerimiento.</h1><div class="av-contact-intro"><a class="contact-number" href="tel:+51920384374">+51 920 384 374</a><p>Lima Metropolitana · Atención previa coordinación.<br>Responderemos a la brevedad.</p></div><div class="av-contact-routes" id="solicitudes"><h2>¿Qué deseas cotizar?</h2><nav aria-label="Canales de cotización"><a href="cotizar.html#quote-form"><strong>Pantallas LED</strong><span>Completar el formulario técnico</span></a><a href="${wa('sonido profesional')}" target="_blank" rel="noopener"><strong>Sonido profesional</strong><span>Compartir el requerimiento por WhatsApp</span></a><a href="${wa('iluminación profesional')}" target="_blank" rel="noopener"><strong>Iluminación</strong><span>Consultar la propuesta por WhatsApp</span></a><a href="${wa('una solución audiovisual integral')}" target="_blank" rel="noopener"><strong>Solución integral</strong><span>Coordinar varios servicios por WhatsApp</span></a><a href="publicidad-led.html#pauta"><strong>Publicidad en el Monumental</strong><span>Enviar la solicitud de campaña</span></a></nav></div><p class="corporate-consent">Los servicios, contratos y comprobantes de pago son gestionados y emitidos por Mentora International S.A.C.</p></div></section>`);

// Existing utility pages retain their routes and functions, with distinct purposes.
page('eventos.html','events','Aplicaciones audiovisuales por tipo de evento','Criterios de planificación audiovisual para conferencias, lanzamientos, eventos institucionales, sociales y conciertos. Orienta el brief de tu evento con SPECTRA RENTAL.',`
<section class="av-events av-space"><div class="container"><p class="eyebrow">Aplicaciones por formato</p><h1>El programa cambia.<br>Las prioridades, también.</h1><p class="av-events-lead">Usa estas referencias para preparar el brief. La elección de servicios se realiza después de conocer el lugar, los participantes y la dinámica de tu evento.</p><div class="av-event-scenarios"><article><h2>Conferencias y congresos</h2><p>Organiza las intervenciones, las presentaciones y los turnos de preguntas. Define quién estará en escenario y qué contenido acompañará cada bloque.</p><a href="sonido.html">Evaluar las necesidades de audio</a></article><article><h2>Lanzamientos y activaciones</h2><p>Delimita el momento principal de la presentación, la posición del público y la interacción con el producto o mensaje de campaña.</p><a href="pantallas-led.html">Explorar la solución de pantalla</a></article><article><h2>Actos institucionales</h2><p>Considera el orden protocolar, los desplazamientos y la visibilidad de las intervenciones. El programa permite anticipar los cambios técnicos.</p><a href="soluciones-audiovisuales.html">Relacionar los servicios necesarios</a></article><article><h2>Celebraciones y recepciones</h2><p>Separa las zonas de actividad y los momentos del encuentro. Las referencias del espacio ayudan a plantear una ambientación consistente.</p><a href="iluminacion.html">Plantear el ambiente lumínico</a></article><article><h2>Conciertos y presentaciones</h2><p>Comparte el programa artístico y los requerimientos de producción disponibles. Esos documentos orientan el alcance audiovisual que se debe evaluar.</p><a href="contacto.html#solicitudes">Enviar el requerimiento de producción</a></article></div></div></section>`);

// Keep LED imagery and service detail unique to the LED page.
let led=read('pantallas-led.html');
led=led.replace('Tu evento merece<br><span class="gradient-text">verse a gran escala.</span>','Pantallas LED<br><span class="gradient-text">a la medida del escenario.</span>');
led=led.replace('Cotizar pantalla LED <span aria-hidden="true">→</span>','Cotizar pantalla para mi evento');
led=led.replace('Coordinamos con proveedores especializados el montaje, las pruebas, la operación durante el evento y el desmontaje final.','El montaje, las pruebas, la operación durante el evento y el desmontaje se coordinan como parte del servicio de pantalla.');
led=led.replace('Spectra Rental planifica el servicio y coordina su ejecución mediante proveedores especializados.','Spectra Rental define el alcance y coordina la ejecución de la solución visual contratada.');
write('pantallas-led.html',led);

let about=read('nosotros.html');
about=about.replace('Brindamos pantallas LED para eventos corporativos, conciertos, activaciones, conferencias y producciones especiales, además de espacios publicitarios digitales en escenarios deportivos. Nuestra operación integra gestión comercial, planificación y coordinación técnica mediante proveedores especializados.','Comercializamos pantallas LED, sonido e iluminación para eventos corporativos, conciertos, activaciones, conferencias y producciones especiales. También coordinamos soluciones audiovisuales combinadas y espacios publicitarios digitales en escenarios deportivos.');
about=about.replace('<li>Operación mediante proveedores especializados.</li>','<li>Sonido e iluminación según el requerimiento.</li>');
about=about.replace('SPECTRA RENTAL coordina la relación comercial, la planificación y la ejecución de cada servicio mediante proveedores técnicos especializados.','SPECTRA RENTAL centraliza la atención comercial y la planificación del alcance audiovisual.');
about=about.replace('href="cotizar.html">Solicitar cotización','href="contacto.html#solicitudes">Solicitar cotización');
write('nosotros.html',about);

// Avoid photographs reused across utility pages; the reference gallery owns its existing stock set.
let quote=read('cotizar.html');
quote=quote.replace(/<div class="aside-card-media">[\s\S]*?<\/div>/,'').replace(/<img class="tile-photo"[^>]*>/g,'');
quote=quote.replace('<p class="eyebrow">Cotizador guiado</p>','<p class="eyebrow">Cotización de pantallas LED</p>');
quote=quote.replace('<p class="lead">Completa tres pasos. Al finalizar podrás revisar tu solicitud y abrir WhatsApp para enviarla.</p>','<p class="lead">Completa tres pasos para solicitar una pantalla LED. Al finalizar podrás revisar tu solicitud y abrir WhatsApp para enviarla.</p><p class="av-quote-route">¿Buscas sonido, iluminación o varios servicios? <a href="contacto.html#solicitudes">Elige el canal de tu consulta.</a></p>');
write('cotizar.html',quote);
let gallery=read('proyectos.html');
// A gallery is the explicit exception to image reuse, but avoid reusing the LED hero here.
gallery=gallery.replaceAll('assets/reference/led-festival.webp','assets/reference/ref-1.webp');
gallery=gallery.replace(/<button class="gallery-card"[^>]*data-alt="Escenario de festival con pantallas LED de gran formato"[\s\S]*?<\/button>/,'');
gallery=gallery.replace(/<section class="section section--panel"><div class="container"><div class="section-head reveal"><p class="eyebrow">Claves de una solución audiovisual[\s\S]*?<\/section>/,'');
gallery=gallery.replace('Montaje, pantalla y <span class="gradient-text">operación técnica.</span>','Referencias visuales <span class="gradient-text">para planificar tu evento.</span>');
gallery=gallery.replaceAll('Ponente y pantalla en una conferencia','Presentación en conferencia con proyección').replaceAll('Salón de eventos con escenario y pantalla','Disposición de un salón de eventos').replaceAll('Recepción social con pantallas y ambientación','Ambientación de una recepción social');
gallery=gallery.replace('posibles aplicaciones de pantallas LED','posibles aplicaciones audiovisuales');
gallery=gallery.replace('href="cotizar.html">Solicitar evaluación →','href="contacto.html#solicitudes">Solicitar evaluación');
gallery=gallery.replace('Max Raber y Daniel Lincoln','Max Raber');
write('proyectos.html',gallery);

for(const file of readdirSync(root).filter(x=>x.endsWith('.html'))){
 let html=read(file);
 html=html.replace(/<header class="site-header">[\s\S]*?<\/header>/,header);
 if(!html.includes('css/audiovisual.css'))html=html.replace('</head>','<link rel="stylesheet" href="css/audiovisual.css">\n</head>');
 html=html.replace(/<p class="footer-copy">[\s\S]*?<\/p>/,'<p class="footer-copy">Servicios audiovisuales para eventos y publicidad LED en Lima Metropolitana.</p>');
 const explore=html.indexOf('<p class="footer-title">Explorar</p>');
 if(explore>=0){
  const linksStart=html.indexOf('<div class="footer-links">',explore),linksEnd=html.indexOf('</div>',linksStart);
  html=html.slice(0,linksStart)+`<div class="footer-links">${services.map(([url,,label])=>`<a href="${url}">${label}</a>`).join('')}<a href="eventos.html">Aplicaciones por evento</a><a href="proyectos.html">Galería referencial</a><a href="contacto.html#solicitudes">Cotizaciones</a>`+html.slice(linksEnd);
 }
 const desc=html.match(/<meta name="description" content="([^"]*)"/)[1];
 const title=html.match(/<title>(.*?)<\/title>/)[1];
 html=html.replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${title}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${desc}">`);
 // Generic floating contact stays relevant outside the LED rental journey.
 if(!['pantallas-led.html','publicidad-led.html','cotizar.html'].includes(file)) html=html.replace(/(<a class="wa-float" href=")[^"]+/,`$1${wa('servicios audiovisuales')}`).replace('aria-label="Cotizar por WhatsApp"','aria-label="Consultar por WhatsApp"');
 write(file,html);
}
